spring: 
  application:
    name: configclient
  datasource:
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vss?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
  jpa:
    database: mysql
    show-sql: true
  session:
    store-type: none






